name: random_pick

on: [pull_request, push]

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: master
      flutter_version: 3.8.0

      min_coverage: 90
